# Generated by Django 3.2.8 on 2021-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 's'), ('Medium', 'm'), ('Large', 'l'), ('XLarge', 'xl')], max_length=20, null=True, verbose_name='ProductSize'),
        ),
    ]
