# Generated by Django 3.2.8 on 2021-11-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(blank=True, max_length=50, null=True, verbose_name='BrandName')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='Categories'),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(blank=True, max_length=50, null=True, verbose_name='BrandName')),
                ('product', models.ManyToManyField(blank=True, null=True, to='Store.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.brand', verbose_name='brand'),
        ),
    ]
