# Generated by Django 3.2.8 on 2021-11-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20211101_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='Categories', verbose_name='CategoryImage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='Products', verbose_name='ProductImageUrl'),
        ),
    ]
