# Generated by Django 3.2.8 on 2021-11-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_auto_20211101_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
