# Generated by Django 3.2.8 on 2021-11-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='Store.Color', verbose_name='ProductColor'),
        ),
    ]
