# Generated by Django 3.2.8 on 2021-11-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_auto_20211101_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='Store.Category', verbose_name='category'),
        ),
    ]
