# Generated by Django 3.2.8 on 2021-11-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_auto_20211102_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'XLarge')], max_length=20, null=True, verbose_name='ProductSize'),
        ),
    ]
