# Generated by Django 3.2.8 on 2021-12-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0023_auto_20211204_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='orderQuantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Order Quantity'),
        ),
        migrations.CreateModel(
            name='WishlistItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishQuantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='WishList Quantity')),
                ('dateAdded', models.DateTimeField(auto_now_add=True, verbose_name='DateTime Added')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.product', verbose_name='product')),
                ('wish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.order', verbose_name='order')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, verbose_name='Date Ordered')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.customer', verbose_name='customer')),
            ],
        ),
    ]
