# Generated by Django 3.2.8 on 2021-12-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0026_alter_wishlistitems_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='orderQuantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Order Quantity'),
        ),
        migrations.AlterField(
            model_name='wishlistitems',
            name='wishQuantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='WishList Quantity'),
        ),
    ]
