# Generated by Django 3.2.8 on 2022-01-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0030_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryDescription',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CategoryDescription'),
        ),
    ]
