# Generated by Django 3.2.8 on 2022-02-14 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0031_category_categorydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='County',
            field=models.CharField(max_length=50, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='DateAdded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='Email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='FirstName',
            field=models.CharField(max_length=200, null=True, verbose_name='FirstName'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='LastName',
            field=models.CharField(max_length=200, null=True, verbose_name='LastName'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='SubCounty',
            field=models.CharField(max_length=50, null=True, verbose_name='SubCounty'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='Telephone',
            field=models.IntegerField(null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='Town',
            field=models.CharField(max_length=50, null=True, verbose_name='Town'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.order', verbose_name='Order'),
        ),
    ]
